apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gotenberg
  labels: { {{- include "viewer.labels" . | nindent 4 }} }
spec:
  type: ClusterIP
  ports: [{ port: 3000, targetPort: 3000, name: http }]
  selector: { app.kubernetes.io/name: document-viewer, app.kubernetes.io/component: gotenberg }
