apiVersion: v2
name: document-viewer
description: Safe document renderer for KYC/AML
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/jhested/document-viewer
sources: [https://github.com/jhested/document-viewer]
maintainers:
  - name: Jimmi Hested
